# Generated by Django 4.0.4 on 2022-06-03 06:15

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gateway.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarriosFk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreBarrios', models.CharField(max_length=100, unique=True, verbose_name='Barrio')),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
            },
        ),
        migrations.CreateModel(
            name='CiuuFk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCiuu', models.CharField(max_length=300, unique=True, verbose_name='CIUU')),
            ],
            options={
                'verbose_name': 'CIUU',
                'verbose_name_plural': 'CIUU',
            },
        ),
        migrations.CreateModel(
            name='DependenciasFK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDependencia', models.CharField(max_length=100, unique=True, verbose_name='Dependencia')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivilFk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstadoCivil', models.CharField(max_length=50, unique=True, verbose_name='Estado Civil')),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civiles',
            },
        ),
        migrations.CreateModel(
            name='EtniaFK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEtnia', models.CharField(max_length=100, unique=True, verbose_name='Etnia')),
            ],
            options={
                'verbose_name': 'Etnia',
                'verbose_name_plural': 'Etnias',
            },
        ),
        migrations.CreateModel(
            name='NacionalidadFk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreNacionalidad', models.CharField(max_length=100, unique=True, verbose_name='Nacionalidad')),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
            },
        ),
        migrations.CreateModel(
            name='TipoDocFk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoDoc', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='VulnerabilidadFk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreVulnerabilidad', models.CharField(max_length=150, unique=True, verbose_name='Vulnerabilidad')),
            ],
            options={
                'verbose_name': 'Vulnerabilidad',
                'verbose_name_plural': 'Vulnerabilidades',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100, verbose_name='Número de documento')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono1', models.CharField(max_length=50, verbose_name='Telefono 1')),
                ('telefono2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono 2')),
                ('politicaTratamiento', models.BooleanField()),
                ('aceptoTerminosCondiciones', models.BooleanField()),
                ('barrio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gateway.barriosfk', verbose_name='Barrio')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tipoDocumento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gateway.tipodocfk', verbose_name='Tipo de Documento')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserFuncionario',
            fields=[
            ],
            options={
                'verbose_name': 'Usuario Funcionario',
                'verbose_name_plural': 'Usuarios Funcionarios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gateway.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PersonaGeneralPerfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('fechaNacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otros')], default='F', max_length=50, verbose_name='Genero')),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('estadoCivil', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.estadocivilfk', verbose_name='Estado Civil')),
                ('etnia', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.etniafk', verbose_name='Etnia')),
                ('nacionalidad', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.nacionalidadfk', verbose_name='Nacionalidad')),
                ('vulnerabilidad', models.ManyToManyField(to='gateway.vulnerabilidadfk')),
            ],
            options={
                'verbose_name': 'Persona General Perfil',
                'verbose_name_plural': 'Personas General Perfil',
            },
        ),
        migrations.CreateModel(
            name='FuncionarioImebuPerfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otros')], default='F', max_length=50, verbose_name='Genero')),
                ('cargo', models.CharField(default=1, max_length=200, verbose_name='Cargo')),
                ('contrato', models.CharField(max_length=200, verbose_name='Contrato')),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('Dependencia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gateway.dependenciasfk')),
                ('estadoCivil', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.estadocivilfk')),
                ('etnia', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.etniafk')),
                ('nacionalidad', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.nacionalidadfk')),
                ('vulnerabilidad', models.ManyToManyField(to='gateway.vulnerabilidadfk')),
            ],
            options={
                'verbose_name': 'Funcionario Imebu',
                'verbose_name_plural': 'Funcionarios Imebu',
            },
        ),
        migrations.CreateModel(
            name='EmpresaGeneralPerfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombreEmpresa', models.CharField(max_length=200, verbose_name='Nombre de Empresa')),
                ('nombreRepresentante', models.CharField(max_length=200, verbose_name='Nombre de Representante')),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('CIIU', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gateway.ciuufk')),
            ],
            options={
                'verbose_name': 'Empresa General Perfil',
                'verbose_name_plural': 'Empresas General Perfil',
            },
        ),
        migrations.CreateModel(
            name='DocumentosPersonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDocumento', models.CharField(max_length=100, verbose_name='Nombre Documento')),
                ('documento', models.FileField(upload_to=gateway.models.user_directory_path_persona, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Documento')),
                ('estado', models.CharField(choices=[('A', 'Aceptado'), ('ER', 'En revisión'), ('R', 'Rechazado')], default='ER', max_length=50, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, default='Sin observaciones', null=True, verbose_name='Observaciones')),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.personageneralperfil')),
            ],
            options={
                'verbose_name': 'Documento Persona',
                'verbose_name_plural': 'Documentos Persona',
            },
        ),
        migrations.CreateModel(
            name='DocumentosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDocumento', models.CharField(max_length=100, verbose_name='Nombre Documento')),
                ('documento', models.FileField(upload_to=gateway.models.user_directory_path_empresa, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Documento')),
                ('estado', models.CharField(choices=[('A', 'Aceptado'), ('ER', 'En revisión'), ('R', 'Rechazado')], default='ER', max_length=50, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, default='Sin observaciones', null=True, verbose_name='Observaciones')),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.empresageneralperfil')),
            ],
            options={
                'verbose_name': 'Documento Empresa',
                'verbose_name_plural': 'Documentos Empresa',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('username', 'tipoDocumento'), name='id_general'),
        ),
        migrations.AddConstraint(
            model_name='empresageneralperfil',
            constraint=models.UniqueConstraint(fields=('user', 'nombreEmpresa'), name='id_dueñoEmpresa'),
        ),
        migrations.AddConstraint(
            model_name='documentospersonas',
            constraint=models.UniqueConstraint(fields=('persona', 'documento'), name='id_documento_persona'),
        ),
        migrations.AddConstraint(
            model_name='documentospersonas',
            constraint=models.UniqueConstraint(fields=('persona', 'nombreDocumento'), name='nombre_documento_persona'),
        ),
        migrations.AddConstraint(
            model_name='documentosempresa',
            constraint=models.UniqueConstraint(fields=('empresa', 'documento'), name='id_documento_empresa'),
        ),
        migrations.AddConstraint(
            model_name='documentosempresa',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombreDocumento'), name='nombre_documento_empresa'),
        ),
    ]
