# Generated by Django 4.0.4 on 2022-06-03 06:15

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreActividad', models.CharField(max_length=150, verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='fase1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('numeroDocumento', models.CharField(max_length=150, verbose_name='Número de Documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono1', models.CharField(max_length=50, verbose_name='Telefono 1')),
                ('telefono2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono 2')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('tipoPersona', models.CharField(choices=[('EmpresaEmprendedor', 'Empresa (Emprendedor)'), ('Microempresario', 'Micro empresario'), ('Independiente', 'Independiente o persona con idea de negocio'), ('Empresa', 'Empresa')], default='EmpresaEmprendedor', max_length=150, verbose_name='Tipo de Persona')),
                ('politicaTratamiento', models.BooleanField()),
                ('aceptoTerminosCondiciones', models.BooleanField()),
                ('tipoDocumento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gateway.tipodocfk', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Informacion Fase 1',
                'verbose_name_plural': 'Informacion Fase 1',
            },
        ),
        migrations.CreateModel(
            name='fase2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoSolicitado', models.DecimalField(decimal_places=2, default=0, max_digits=11, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Solicitado')),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otros')], default='F', max_length=50, verbose_name='Genero')),
                ('comuna', models.CharField(max_length=50, verbose_name='Comuna')),
                ('estrato', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Estrato')),
                ('direccionComercial', models.CharField(max_length=100, verbose_name='Direccion Comercial')),
                ('fechaNacimiento', models.DateField()),
                ('escolaridad', models.CharField(choices=[('Primaria', 'Primaria'), ('Bachiller', 'Bachiller'), ('Pregrado', 'Pregrado'), ('Especialidad', 'Especialidad'), ('Maestria', 'Maestria'), ('Doctorado', 'Doctorado')], default='Primaria', max_length=50, verbose_name='Escolaridad')),
                ('formalidad', models.CharField(choices=[('Rut', 'Rut'), ('Cedula', 'Cedula'), ('ICA', 'ICA'), ('Informal', 'Informal')], default='Rut', max_length=50, verbose_name='Formalidad')),
                ('actividad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='banca_ciudadana.actividades', verbose_name='Actividad')),
                ('barrio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gateway.barriosfk', verbose_name='Barrio')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banca_ciudadana.fase1')),
            ],
            options={
                'verbose_name': 'Informacion Fase 2',
                'verbose_name_plural': 'Informacion Fase 2',
            },
        ),
        migrations.CreateModel(
            name='funcionarioOperador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('fechaNacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otros')], default='F', max_length=50, verbose_name='Genero')),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Funcionario Operador',
                'verbose_name_plural': 'Funcionarios Operador',
            },
        ),
        migrations.CreateModel(
            name='operador',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Operador')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
            },
        ),
        migrations.CreateModel(
            name='sectores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSector', models.CharField(max_length=150, verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='tipologias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipologia', models.CharField(max_length=100, verbose_name='Tipologia')),
            ],
            options={
                'verbose_name': 'Tipologia',
                'verbose_name_plural': 'Tipologias',
            },
        ),
        migrations.CreateModel(
            name='UserOperador',
            fields=[
            ],
            options={
                'verbose_name': 'Usuario Operador',
                'verbose_name_plural': 'Usuarios Operador',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gateway.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(verbose_name='Observadores')),
                ('estado', models.CharField(choices=[('A', 'ACEPTADO'), ('R', 'RECHAZADO'), ('EP', 'En PROCESO')], max_length=100, verbose_name='Estado')),
                ('funcionarioOperador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banca_ciudadana.funcionariooperador', verbose_name='Funcionario Operador')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banca_ciudadana.fase2', verbose_name='Persona')),
                ('tipologias', models.ManyToManyField(to='banca_ciudadana.tipologias')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
            },
        ),
        migrations.CreateModel(
            name='opcionesOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banca_ciudadana.operador', verbose_name='Operador')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banca_ciudadana.fase2', verbose_name='Persona')),
                ('tipologias', models.ManyToManyField(to='banca_ciudadana.tipologias')),
            ],
            options={
                'verbose_name': 'Opcion del Operador',
                'verbose_name_plural': 'Opciones del Operador',
            },
        ),
        migrations.AddField(
            model_name='funcionariooperador',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banca_ciudadana.operador', verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='fase2',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='banca_ciudadana.sectores', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='fase2',
            name='vulnerabilidad',
            field=models.ManyToManyField(to='gateway.vulnerabilidadfk'),
        ),
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banca_ciudadana.proceso', verbose_name='Proceso')),
                ('tipologias', models.ManyToManyField(to='banca_ciudadana.tipologias')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
